### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by steveoh** [agrc/view-counter#1]
Did you consider sending the window.location values to the function rather than relying on the [referrer/referer](https://en.wikipedia.org/wiki/HTTP_referer) header? It seems to me that it would be more reliable since plugins/extensions will remove those. Google analytics only shows the pathname as well.

**Comment by stdavis** [comment]
No, I didn't consider plugins/extensions removing the referrer. I can definitely add a parameter to the service and send it something from `window.location`.

I was planning on using the entire URL to prevent counts for pages hosted in development.

What do you think about using `window.location.href`?
![image](https://user-images.githubusercontent.com/1326248/37065863-06947cdc-2160-11e8-895d-dff2649555c6.png)

[Browser compatibility doesn't seem to be an issue](https://developer.mozilla.org/en-US/docs/Web/API/Location).

**Comment by steveoh** [comment]
Yes I think that would be great. Then ignore anything not from gis.Utah.gov so the previews and stuff are ignored?

**Comment by stdavis** [comment]
Ya, I wondered about that. I don't think that it's an issue to leave the previews and localhost stuff in there. It makes testing the view counter code easier and we are nowhere close to getting out of the free tier on the datastore.

I did wonder about restricting by referrer to just localhost, *gis-utah-gov.netlify.com, and gis.utah.gov just to prevent anyone else from hitting the service.

**Comment by stdavis** [comment]
Just realized, if I use the referrer to lock it down then there's no reason to use `window.location.href`, is there? Maybe I shouldn't worry about locking it down? Thoughts?

**Comment by steveoh** [comment]
I don't think there is any reason to abuse it but I wouldn't be surprised. Maybe referrer is the right way after all. We should probably look at both variants of the referrer header and respect the do not track header?

**Comment by stdavis** [comment]
Ya, the more I thought about it the more I thought that using the referrer header is the way to go. I vote that we stick with it.

I believe that `request.get('referrer')` checks for both spellings so we are good there.

I looked at the do not track header and am not sure that it applies to this service. From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT):
>It lets users indicate whether they would prefer privacy rather than personalized content.

We not tracking the user. We're just counting page views. I say that we don't worry about it. However, if you feel differently, I can easily add it.

**Comment by stdavis** [comment]
Closing this for now but feel free to re-open if you want to, @steveoh.
