### ISSUE TITLE
Incorrect view counts caused by duplicate keys

### ISSUE THREAD

**Issue by steveoh** [agrc/view-counter#10]
the url should strip or ensure  the trailing `/` to avoid duplicate keys in the memory store. Anchor links should be stripped as well as query strings.

![image](https://user-images.githubusercontent.com/325813/123722801-4d3bb100-d846-11eb-9566-96a01d694b86.png)

The data needs to be de-duplicated with the values summed to be more accurate.

**Comment by stdavis** [comment]
- [x] fix the js on the website that sends the urls
- [x] de-dup the data store

**Comment by stdavis** [comment]
Data has been de-duped with this script: https://gist.github.com/stdavis/49d370f541ea994c75522c25aa7bb764
